### ISSUE TITLE
Enable bot for dependencies updates

### ISSUE THREAD

**Issue by AlexWayfer** [lostisland/faraday-middleware-template#11]
It'd be nice to get PRs by some bot with `Gemfile` updates.

I don't think any bot will be able to parse `template/gem_name.gemspec.erb`, but [we have specs for outdated dependencies in the template](https://github.com/lostisland/faraday-middleware-template/blob/6badedb/spec/generated_project_spec.rb#L163-L171).

Options: Dependabot (almost official by GitHub, but doesn't support grouped updates yet), Renovate (seems powerful), Depfu (my own choice).

**Comment by iMacTia** [comment]
That's a great point, otherwise new projects will be created with already outdated dependencies 👍

**Comment by AlexWayfer** [comment]
Please, enable at least Dependabot for this project.
